---
abstract: 'use Apple Address Book as the addex source'
author:
  - 'Ricardo SIGNES, C<< <rjbs@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.88'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: App::Addex::AddressBook::Apple
name: App-Addex-AddressBook-Apple
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  App::Addex: 0.007
  Encode: 0
  Mac::Glue: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/rjbs/app-addex-addressbook-apple
version: 0.016
