---
abstract: 'use Apple Address Book as the addex source (doomed)'
author:
  - 'Ricardo SIGNES <rjbs@cpan.org>'
build_requires:
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Addex-AddressBook-Apple
requires:
  App::Addex::AddressBook: 0
  App::Addex::Entry::EmailAddress: 0
  Encode: 0
  Mac::Glue: 0
  base: 0
  perl: 5.008
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/rjbs/App-Addex-AddressBook-Apple/issues
  homepage: https://github.com/rjbs/App-Addex-AddressBook-Apple
  repository: https://github.com/rjbs/App-Addex-AddressBook-Apple.git
version: 0.018
x_Dist_Zilla:
  perl:
    version: 5.018001
  plugins:
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      name: '@Filter/Git::GatherDir'
      version: 2.017
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: '@Filter/CheckPrereqsIndexed'
      version: 0.009
    -
      class: Dist::Zilla::Plugin::CheckExtraTests
      name: '@Filter/CheckExtraTests'
      version: 0.016
    -
      class: Dist::Zilla::Plugin::PromptIfStale
      name: '@Filter/RJBS-Outdated'
      version: 0.013
    -
      class: Dist::Zilla::Plugin::PromptIfStale
      name: '@Filter/CPAN-Outdated'
      version: 0.013
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Filter/@Filter/PruneCruft'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Filter/@Filter/ManifestSkip'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Filter/@Filter/MetaYAML'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::License
      name: '@Filter/@Filter/License'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Filter/@Filter/Readme'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Filter/@Filter/ExecDir'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Filter/@Filter/ShareDir'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Filter/@Filter/MakeMaker'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Filter/@Filter/Manifest'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Filter/@Filter/ConfirmRelease'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Filter/@Filter/UploadToCPAN'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Filter/AutoPrereqs'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@Filter/Git::NextVersion'
      version: 2.017
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Filter/PkgVersion'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Filter/MetaConfig'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Filter/MetaJSON'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Filter/NextRelease'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::Test::ChangesHasContent
      name: '@Filter/Test::ChangesHasContent'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Filter/PodSyntaxTests'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: '@Filter/ReportVersions::Tiny'
      version: 1.10
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: '@Filter/TestMoreWithSubtests'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::PodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          config_plugin: '@RJBS'
          finder:
            - ':InstallModules'
            - ':ExecFiles'
          plugins:
            -
              class: Pod::Weaver::Plugin::EnsurePod5
              name: '@CorePrep/EnsurePod5'
              version: 4.004
            -
              class: Pod::Weaver::Plugin::H1Nester
              name: '@CorePrep/H1Nester'
              version: 4.004
            -
              class: Pod::Weaver::Section::Name
              name: '@RJBS/Name'
              version: 4.004
            -
              class: Pod::Weaver::Section::Version
              name: '@RJBS/Version'
              version: 4.004
            -
              class: Pod::Weaver::Section::Region
              name: '@RJBS/Prelude'
              version: 4.004
            -
              class: Pod::Weaver::Section::Generic
              name: '@RJBS/Synopsis'
              version: 4.004
            -
              class: Pod::Weaver::Section::Generic
              name: '@RJBS/Description'
              version: 4.004
            -
              class: Pod::Weaver::Section::Generic
              name: '@RJBS/Overview'
              version: 4.004
            -
              class: Pod::Weaver::Section::Generic
              name: '@RJBS/Stability'
              version: 4.004
            -
              class: Pod::Weaver::Section::Collect
              name: Attributes
              version: 4.004
            -
              class: Pod::Weaver::Section::Collect
              name: Methods
              version: 4.004
            -
              class: Pod::Weaver::Section::Collect
              name: Functions
              version: 4.004
            -
              class: Pod::Weaver::Section::Leftovers
              name: '@RJBS/Leftovers'
              version: 4.004
            -
              class: Pod::Weaver::Section::Region
              name: '@RJBS/postlude'
              version: 4.004
            -
              class: Pod::Weaver::Section::Authors
              name: '@RJBS/Authors'
              version: 4.004
            -
              class: Pod::Weaver::Section::Legal
              name: '@RJBS/Legal'
              version: 4.004
            -
              class: Pod::Weaver::Plugin::Transformer
              name: '@RJBS/List'
              version: 4.004
      name: '@Filter/PodWeaver'
      version: 4.002
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@Filter/GithubMeta'
      version: 0.42
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Filter/@Git/Check'
      version: 2.017
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Filter/@Git/Commit'
      version: 2.017
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Filter/@Git/Tag'
      version: 2.017
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Filter/@Git/Push'
      version: 2.017
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 5.006
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 5.006
